2019-07-03 14:35:01,600 ERROR: Exception on /follow/susan [GET] [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780
Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/routes.py", line 140, in follow
    return redirect(url_for('user', username=username))
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'user_page' instead?
2019-07-03 14:35:33,071 ERROR: Exception on /follow/susan [GET] [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780
Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/routes.py", line 140, in follow
    return redirect(url_for('user_page', username=username))
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'user_page' instead?
